// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPESF7sBvA8xc1610Iqc1C4r7Z2IbGOGE',
    appId: '1:523797651840:web:393cf91aa7a027601ca165',
    messagingSenderId: '523797651840',
    projectId: 'rutapp-e5632',
    authDomain: 'rutapp-e5632.firebaseapp.com',
    storageBucket: 'rutapp-e5632.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwkhLwzMCrpYlKLPy5_YgdfbX4E6ZGCqo',
    appId: '1:523797651840:android:4d734276f8dd08101ca165',
    messagingSenderId: '523797651840',
    projectId: 'rutapp-e5632',
    storageBucket: 'rutapp-e5632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMzZcFQZza5TpUxZRqfngyzaTZACKElqE',
    appId: '1:523797651840:ios:0fd58947ba3fc0c71ca165',
    messagingSenderId: '523797651840',
    projectId: 'rutapp-e5632',
    storageBucket: 'rutapp-e5632.appspot.com',
    iosBundleId: 'com.uptap.rutapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMzZcFQZza5TpUxZRqfngyzaTZACKElqE',
    appId: '1:523797651840:ios:55d2ac0df7dc05161ca165',
    messagingSenderId: '523797651840',
    projectId: 'rutapp-e5632',
    storageBucket: 'rutapp-e5632.appspot.com',
    iosBundleId: 'com.uptap.rutapp.RunnerTests',
  );
}
